test@

diff --git a/.github/workflows/ic-ui-kit-release-check.yml b/.github/workflows/ic-ui-kit-release-check.yml
--- a/.github/workflows/ic-ui-kit-release-check.yml
+++ b/.github/workflows/ic-ui-kit-release-check.yml
@@ -33,10 +33,18 @@ jobs:
         run: |
           REACT_VERSION=$(echo "${{ env.VERSION }}" | grep '@ukic/react' | sed -n 's/.*=> \([0-9.]*\).*/\1/p')
           WEB_COMPONENTS_VERSION=$(echo "${{ env.VERSION }}" | grep '@ukic/web-components' | sed -n 's/.*=> \([0-9.]*\).*/\1/p')
+          CANARY_REACT_VERSION=$(echo "${{ env.VERSION }}" | grep '@ukic/canary-react' | sed -n 's/.*=> \([0-9.]*\).*/\1/p')
+          CANARY_WEB_COMPONENTS_VERSION=$(echo "${{ env.VERSION }}" | grep '@ukic/canary-web-components' | sed -n 's/.*=> \([0-9.]*\).*/\1/p')
           echo "React version: $REACT_VERSION"
           echo "Web Components version: $WEB_COMPONENTS_VERSION"
+          echo "Canary React version: $CANARY_REACT_VERSION"
+          echo "Canary Web Components version: $CANARY_WEB_COMPONENTS_VERSION"
           if [ "$REACT_VERSION" != "$WEB_COMPONENTS_VERSION" ]; then
             echo "Error: The versions of @ukic/react and @ukic/web-components packages are not identical."
+            exit 1
+          fi
+          if [ "$CANARY_REACT_VERSION" != "$CANARY_WEB_COMPONENTS_VERSION" ]; then
+            echo "Error: The versions of @ukic/canary-react and @ukic/canary-web-components packages are not identical."
             exit 1
           fi
       #TODO: update the details to the variables in other files
